name: checkout
description: git checkout
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
          ref: "feature_1" 
    - uses: actions/setup-java@v4
      with:
       distribution: 'temurin'
       java-version: '17'      