name: build docker image

on:
    workflow_call:
      secrets:
        GITHUB_TOKEN:
         required: true

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
                ref: main
        - name: package
          run: mvn clean install
          shell: bash
        - name: Build an image from Dockerfile
          run: |
            docker build -t docker.io/hdteck/springboot.backend:${{ github.sha }} .
          shell: bash
          
    release:
      needs: 'build'
      uses: ./.github/workflows/workflow-release.yml
      secrets: inherit
