name: release
on:
  workflow_call:
  
jobs:
    build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: main
        - name: Update branch protection
          uses: Hatzelencio/branch-protection@v1.0.0
          with:
           path: .github/config/main-branch-protection.yml
          env:
            GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}    
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          with:
            tag_name: "v1.1"
            release_name: Release ${{ github.head_ref }}
            body: |
              Changes in this Release
              - Release de pullrquest "${{ github.event.pull_request.number }}"
              - Rama ${{ github.head_ref }}
            draft: false
            prerelease: false